# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    container: phelpsw/msp430-build:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      # Run tests
      - name: Run Tests
        run: |
          meson testing
          ninja -C testing test

      # Run tests
      - name: Run Tests
        run: |
          meson testing
          ninja -C testing test
          
      # Build release
      - name: Build
        run: |
          meson --cross-file msp430.txt release
          ninja -C release
        
      # Upload build artifact
      - uses: actions/upload-artifact@v2
        with:
          name: flash_blink
          path: release/src/blink.elf
